version: "3"

services:
  router:
    build: ./router
    command: router
    cap_add:
      - NET_ADMIN
    expose:
      - "8080"
    networks:
      - iot
    user: root

  echo-server:
    build: ./devices/tcp-echo-server
    command: tcp-echo-server
    expose:
      - "8080"
    networks:
      - iot

  echo-client:
    build: ./devices/tcp-echo-client
    command: tcp-echo-client
    networks:
      - iot

networks:
  iot:
    ipam:
      config:
        -subnet: 172.18.0.0/24
