version: "3"

networks:
  iot:
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  router:
    build: ./router
    command: router
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"
    networks:
      iot:
        ipv4_address: 172.18.0.2
    environment:
      ECHO_SERVER: 172.18.0.3
      ECHO_CLIENT: 172.18.0.4
      SH_CONTROLLER: 172.18.0.5
      WEATHER_SENSOR: 172.18.0.6
      THERMOSTAT: 172.18.0.7
    deploy:
      restart_policy:
        condition: on-failure

  smart_home_controller:
    build: ./devices/smart_home_controller
    command: smart_home_controller 172.18.0.2 172.18.0.6 172.18.0.7
    cap_add:
      - NET_ADMIN
    expose:
      - "8080"
    networks:
      iot:
        ipv4_address: 172.18.0.5
    deploy:
      restart_policy:
        condition: on-failure

  weather_sensor:
    build: ./devices/weather_sensor
    command: weather_sensor 172.18.0.2 172.18.0.5
    cap_add:
      - NET_ADMIN
    networks:
      iot:
        ipv4_address: 172.18.0.6
    deploy:
      restart_policy:
        condition: on-failure

  thermostat:
    build: ./devices/thermostat
    command: thermostat 172.18.0.2 172.18.0.5
    cap_add:
      - NET_ADMIN
    expose:
      - "8080"
    networks:
      iot:
        ipv4_address: 172.18.0.7
    deploy:
      restart_policy:
        condition: on-failure

    # echo-server:
    #   build: ./devices/tcp-echo-server
    #   command: tcp-echo-server 172.18.0.2 172.18.0.4
    #   cap_add:
    #     - NET_ADMIN
    #   expose:
    #     - "8080"
    #   networks:
    #     iot:
    #       ipv4_address: 172.18.0.3
    #   deploy:
    #     restart_policy:
    #       condition: on-failure

    # echo-client:
    #   build: ./devices/tcp-echo-client
    #   command: tcp-echo-client 172.18.0.2 172.18.0.3
    #   cap_add:
    #     - NET_ADMIN
    #   networks:
    #     iot:
    #       ipv4_address: 172.18.0.4
    #   deploy:
    #     restart_policy:
    #       condition: on-failure

