version: "3"

networks:
  iot:
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
  analysis:

services:
  router:
    build: ./router
    command: router
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"
    networks:
      iot:
        ipv4_address: 172.18.0.2
    environment:
      # ECHO_SERVER: 172.18.0.3
      # ECHO_CLIENT: 172.18.0.4
      SH_CONTROLLER: 172.18.0.5
      WEATHER_SENSOR: 172.18.0.6
      THERMOSTAT: 172.18.0.7
      GARAGE_DOOR: 172.18.0.8
      FRIDGE: 172.18.0.9
      LIGHTS: 172.18.0.10
      MOTION_SENSOR: 172.18.0.11
    deploy:
      restart_policy:
        condition: on-failure

  smart_home_controller:
    build: ./devices/smart_home_controller
    command: smart_home_controller 172.18.0.2 172.18.0.6 172.18.0.7 172.18.0.8 172.18.0.9
    cap_add:
      - NET_ADMIN
    expose:
      - "8080"
    networks:
      iot:
        ipv4_address: 172.18.0.5
    deploy:
      restart_policy:
        condition: on-failure

  weather_sensor:
    build: ./devices/weather_sensor
    command: weather_sensor 172.18.0.2 172.18.0.5 172.18.0.7
    cap_add:
      - NET_ADMIN
    networks:
      iot:
        ipv4_address: 172.18.0.6
    deploy:
      restart_policy:
        condition: on-failure

  thermostat:
    build: ./devices/thermostat
    command: thermostat 172.18.0.2 172.18.0.5 172.18.0.6
    cap_add:
      - NET_ADMIN
    expose:
      - "8080"
    networks:
      iot:
        ipv4_address: 172.18.0.7
    deploy:
      restart_policy:
        condition: on-failure

  garage_door:
    build: ./devices/garage_door
    command: garage_door 172.18.0.2 172.18.0.5
    cap_add:
      - NET_ADMIN
    expose:
      - "8080"
    networks:
      iot:
        ipv4_address: 172.18.0.8
    deploy:
      restart_policy:
        condition: on-failure

  refridgerator:
    build: ./devices/refridgerator
    command: refridgerator 172.18.0.2 172.18.0.5
    cap_add:
      - NET_ADMIN
    networks:
      iot:
        ipv4_address: 172.18.0.9
    deploy:
      restart_policy:
        condition: on-failure

  lights:
    build: ./devices/lights
    command: lights 172.18.0.2 172.18.0.11
    cap_add:
      - NET_ADMIN
    expose:
      - "8080"
    networks:
      iot:
        ipv4_address: 172.18.0.10
    deploy:
      restart_policy:
        condition: on-failure

  motion_sensor:
    build: ./devices/motion_sensor
    command: motion_sensor 172.18.0.2 172.18.0.10
    cap_add:
      - NET_ADMIN
    networks:
      iot:
        ipv4_address: 172.18.0.11
    deploy:
      restart_policy:
        condition: on-failure

  data_aggregation:
    build: ./data_aggregation
    command: python app.py
    networks:
      - iot
      - analysis

  db:
   image: mongo
   environment:
     - MONGO_INITDB_DATABASE=traffic_windows
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=password
   networks:
     - analysis

    # echo-server:
    #   build: ./devices/tcp-echo-server
    #   command: tcp-echo-server 172.18.0.2 172.18.0.4
    #   cap_add:
    #     - NET_ADMIN
    #   expose:
    #     - "8080"
    #   networks:
    #     iot:
    #       ipv4_address: 172.18.0.3
    #   deploy:
    #     restart_policy:
    #       condition: on-failure

    # echo-client:
    #   build: ./devices/tcp-echo-client
    #   command: tcp-echo-client 172.18.0.2 172.18.0.3
    #   cap_add:
    #     - NET_ADMIN
    #   networks:
    #     iot:
    #       ipv4_address: 172.18.0.4
    #   deploy:
    #     restart_policy:
    #       condition: on-failure

