version: "3"

networks:
  iot:
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
  analysis:
  internet:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:

  # ROUTER #########################################################################################
  router:
    build: ../router
    command: router
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"
    networks:
      iot:
        ipv4_address: 172.18.0.20
      internet:
        ipv4_address: 172.20.0.3
    environment:
      SH_CONTROLLER: 172.18.0.5
      WEATHER_SENSOR: 172.18.0.6
      THERMOSTAT: 172.18.0.7
      GARAGE_DOOR: 172.18.0.8
      FRIDGE: 172.18.0.9
      LIGHTS: 172.18.0.10
      MOTION_SENSOR: 172.18.0.11
      TARGET: 172.20.0.2
    deploy:
      restart_policy:
        condition: on-failure

  # DEVICES ########################################################################################
  smart_home_controller:
    build: ../devices/smart_home_controller
    command: smart_home_controller true 172.18.0.20 172.18.0.6 172.18.0.7 172.18.0.8 172.18.0.9 172.20.0.2
    cap_add:
      - NET_ADMIN
    expose:
      - "8080"
    networks:
      iot:
        ipv4_address: 172.18.0.5
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: '0.5G'

  weather_sensor:
    build: ../devices/weather_sensor
    command: weather_sensor true 172.18.0.20 172.18.0.5 172.18.0.7 172.20.0.2
    cap_add:
      - NET_ADMIN
    networks:
      iot:
        ipv4_address: 172.18.0.6
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: '0.5G'

  thermostat:
    build: ../devices/thermostat
    command: thermostat true 172.18.0.20 172.18.0.5 172.18.0.6 172.20.0.2
    cap_add:
      - NET_ADMIN
    expose:
      - "8080"
    networks:
      iot:
        ipv4_address: 172.18.0.7
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: '0.5G'

  garage_door:
    build: ../devices/garage_door
    command: garage_door true 172.18.0.20 172.18.0.5 172.20.0.2
    cap_add:
      - NET_ADMIN
    expose:
      - "8080"
    networks:
      iot:
        ipv4_address: 172.18.0.8
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: '0.5G'

  refridgerator:
    build: ../devices/refridgerator
    command: refridgerator true 172.18.0.20 172.18.0.5 172.20.0.2
    cap_add:
      - NET_ADMIN
    networks:
      iot:
        ipv4_address: 172.18.0.9
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: '0.5G'

  lights:
    build: ../devices/lights
    command: lights true 172.18.0.20 172.18.0.11 172.20.0.2
    cap_add:
      - NET_ADMIN
    expose:
      - "8080"
    networks:
      iot:
        ipv4_address: 172.18.0.10
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: '0.5G'

  motion_sensor:
    build: ../devices/motion_sensor
    command: motion_sensor true 172.18.0.20 172.18.0.10 172.20.0.2
    cap_add:
      - NET_ADMIN
    networks:
      iot:
        ipv4_address: 172.18.0.11
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: '0.5G'

  # ANALYSIS #######################################################################################
  data_aggregation:
    build: ../data_aggregation
    command: python app.py collect 3 ddos_tcp ddos_tcp_3_redux
    restart: always
    volumes:
      - ../data_aggregation:/app
    networks:
      - iot
      - analysis
    depends_on:
      - "db"
      - "garage_door"
      - "lights"
      - "motion_sensor"
      - "refridgerator"
      - "smart_home_controller"
      - "weather_sensor"
      - "thermostat"

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: traffic_windows
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ../mongo:/data/db
    networks:
      - analysis

  # ATTACKER #######################################################################################
  cnc:
    build: ../cnc
    command: python app.py collect
    volumes:
      - ../cnc:/app
    networks:
      - analysis
      - iot
    ports:
      - "8000:8000"

  # VICTIM #########################################################################################
  victim:
    build: ../devices/victim
    command: victim 172.20.0.3 172.18.0.5 172.18.0.6 172.18.0.7 172.18.0.8 172.18.0.9 172.18.0.10 172.18.0.11
    cap_add:
      - NET_ADMIN
    networks:
      internet:
        ipv4_address: 172.20.0.2

