[package]
name = "tcp-echo-server"
version = "0.1.0"
authors = ["Eric McCullough <eric96@live.missouristate.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
